before:
  hooks:
    - go mod download
builds:
    - id: default
      goos:
        - darwin
        - linux
        - windows
      goarch:
        - amd64
      asmflags:
        - all=-trimpath={{.Env.GOPATH}}
      gcflags:
        - all=-trimpath={{.Env.GOPATH}}
      ldflags:
        - -s -w
      env:
        - CGO_ENABLED=0
        - GO111MODULE=on
      mod_timestamp: '{{ .CommitTimestamp }}'
archives:
    - id: default
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
      replacements:
        amd64: 64-bit
        darwin: macOS
        linux: Linux
        windows: Windows
      format: tar.gz
      format_overrides:
        - goos: windows
          format: zip
      files:
        - README.md
        - LICENSE.txt
checksum:
  name_template: 'checksums.txt'
  algorithm: sha512
brews:
    - name: cryptovalues
      tap:
        owner: riussi
        name: cryptovalues-tap
      url_template: "https://github.com/riussi/cryptovalues/releases/{{ .Tag }}/{{ .ArtifactName }}"
      commit_author:
        name: goreleaserbot
        email: juha@riussi.eu
      folder: Formula
      test: |
        system "#{bin}/cryptovalues version"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
